//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePortal_Ganesh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employment_history = new HashSet<employment_history>();
        }
    
        public int emp_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public string pan_num { get; set; }
        public string aadhaar_num { get; set; }
        public string mobile_num { get; set; }
        public string email_id { get; set; }
        public string office_mail { get; set; }
        public string permanent_address { get; set; }
        public string present_address { get; set; }
        public string blood_group { get; set; }
        public string profile_pict { get; set; }
        public System.DateTime doj { get; set; }
        public int emp_level { get; set; }
        public string post_name { get; set; }
        public int basic_pay { get; set; }
        public int house_allowance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employment_history> employment_history { get; set; }
    }
}
